
        name: CI/CD Pipeline
        
        on:
          push:
            branches:
              - main
        
        jobs:
          build:
            runs-on: ubuntu-latest
        
            steps:
              - name: Checkout
                uses: actions/checkout@v2
        
              - name: Set up Node.js
                uses: actions/setup-node@v2
                with:
                  node-version: '14'
        
              - name: Install Dependencies
                run: |
                  npm install
        
              - name: SonarQube Analysis
                run: |
                  curl -o sonar-scanner.zip -L https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-windows.zip
                  echo "C:\Users\vipve\sonar-scanner-5.0.1.3006-windows\bin\sonar-scanner.bat"
        
              - name: Test using Jest
                run: npm test
        
              - name: Run JMeter Tests
                uses: QAInsights/PerfAction@v3.1
                with:
                  test-plan-path: ./CSVSample.jmx
        
              - name: Build Docker image
                run: |
                  docker build -t vipv/kuber:${{ github.run_number }} .
        
              - name: Push Docker image
                run: |
                  docker login -u vipv -p 9092897730
                  docker push vipv/kuber:${{ github.run_number }}
        
              - name: Run Docker Container
                run: |
                  docker run -d -p 8000:8000 vipv/kuber:${{ github.run_number }}
        
