name: Build and Deploy Angular App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install Dependencies
      run: npm install
      working-directory: ./celestradepro  # Set this to the root of your Angular project

    - name: Build Angular App
      run: npm run build
      working-directory: ./celestradepro  # Adjust this to the root of your Angular project

   # - name: Set up Docker Buildx
    #  uses: docker/setup-buildx-action@v1

    - name: Build Docker Image
      run: |
        docker build -t cmtq/cloud:${{ github.run_number }} .

    - name: Log in to Docker Hub
      run: |
        docker login -u cmtq -p 90950047

    - name: Push Docker Image
      run: |
        docker push cmtq/cloud:${{ github.run_number }}

    - name: Run Docker Container
      run: |
        docker run -d -p 8000:8000 cmtq/cloud:${{ github.run_number }}
